# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Neurorobotics workshop
author: Neurocomputing Systems, KTH
logo: ncs.png

# Do *not* execute the notebooks since they have infinite loops
execute:
  execute_notebooks: 'off'

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/ncskth/norse-rl  # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  binderhub_url: "https://mybinder.org/v2/gh/ncskth/norse-rl/HEAD"
  colab_url: "https://colab.research.google.com"
  thebe: true

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
